# This file will be included by the Makefile under the project directory.

###replace ".a" with ".o" ###
FLOAT_OBJ := $(FLOAT:.a=.o)
FLOAT_SRC := $(LIB_COMMON_DIR)/FLOAT.c

### make target ###
$(FLOAT): $(FLOAT_OBJ)
	ar r $(FLOAT) $(FLOAT_OBJ)

# TODO: write a rule for generating $(FLOAT_OBJ)

FLOAT_CFLAGS_EXTRA := -c -m32 -fno-builtin -I $(LIB_COMMON_DIR)

$(FLOAT_OBJ): $(FLOAT_SRC)
	$(CC) $(FLOAT_CFLAGS_EXTRA) $(FLOAT_SRC) -o $(FLOAT_OBJ) 
