# This file will be included by the Makefile under the project directory.

###replace ".a" with ".o" ###
FLOAT_OBJ := $(FLOAT:.a=.o)
FLOAT_SRC := $(FLOAT:.a=.c)
### make target ###
$(FLOAT): $(FLOAT_OBJ)
	ar r $(FLOAT) $(FLOAT_OBJ)

# TODO: write a rule for generating $(FLOAT_OBJ)

CFLAGS_EXTRA := -m32 -fno-builtin
vpath % lib-common
$(FLOAT_OBJ): $(FLOAT_SRC)
	$(call make_command, $(CC),$(FLOAT_CFLAGS_EXTRA), cc $@, $^)
